[project]
name = "designing-with-python"
version = "0.1.0"
description = "Study notes for 'Designing with Python: Programming for a Visual Context' Domestika course"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Ülgen Sarıkavak", email = "foss@ulgenwanders.net" },
]
requires-python = "==3.14.*"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "py5==0.10.11a0",
]

[project.urls]
Homepage = "https://github.com/ulgens/designing-with-python"

[dependency-groups]
dev = [
    "ipdb==0.13.13",
    "ipython==9.15.0",
    "ruff==0.16.0",    # For IDE integrations
]

[tool.uv]
# The earliest version that supports the current lock file revision
required-version = ">=0.8.4"
package = false
